os:
  - windows
  - linux
  - osx
language: node_js
node_js:
    - "12"
install:
  - npm install -g gulp-cli
script:
  - # ======== labiba-transformer
  - cd labiba-transformer
  - npm install --no-optional
  - webpack
  - # ======== labiba-parser
  - cd ..
  - cd labiba-parser
  - npm install
  - npm install gulp
  - gulp build
  - # ======== labiba-ide
  - cd ..
  - cd labiba-ide
  - npm install
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then npm run build-win          ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then npm run build-linux          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then npm run build-mac          ; fi
