language: node_js
node_js:
    - "12"
before_script:
  - npm install -g gulp-cli
script:
  - cd labiba-transformer
  - npm install --no-optional
  - webpack
  - cd ..
  - cd labiba-parser
  - npm install
  - npm install gulp
  - gulp build
  - cd ..
  - cd labiba-ide
  - npm install
  - npm run build
